# Foundry Configuration for Bellve Buildathon
# TESTNET DEPLOYMENT ONLY - Base Sepolia

[profile.default]
  auto_detect_solc = false
  block_timestamp = 1_738_368_000 # Feb 1, 2025
  bytecode_hash = "none"
  evm_version = "cancun"
  fuzz = { runs = 256 }
  gas_reports = ["*"]
  optimizer = true
  optimizer_runs = 200
  out = "out"
  script = "script"
  solc = "0.8.29"
  src = "src"
  test = "test"
  libs = ["lib"]

[profile.ci]
  fuzz = { runs = 1_000 }
  verbosity = 4

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 120
  multiline_func_header = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true

[rpc_endpoints]
  base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
  localhost = "http://localhost:8545"

[etherscan]
  base_sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }

