name: Demo CI - Bellve Buildathon (TESTNET ONLY)

on:
  push:
    branches: [main, develop]
    paths:
      - 'demo/**'
      - '.github/workflows/demo-ci.yml'
  pull_request:
    branches: [main, develop]
    paths:
      - 'demo/**'

jobs:
  test:
    name: Test Demo
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
          cache-dependency-path: 'demo/pnpm-lock.yaml'
      
      - name: Install dependencies
        working-directory: demo
        run: pnpm install --frozen-lockfile
      
      - name: Lint
        working-directory: demo
        run: pnpm lint
        continue-on-error: true
      
      - name: Type check
        working-directory: demo
        run: pnpm exec tsc --noEmit
        continue-on-error: true
      
      - name: Build
        working-directory: demo
        run: pnpm build

