name: Indexer CI - Bellve Buildathon (TESTNET ONLY)

on:
  push:
    branches: [main, develop]
    paths:
      - 'indexer/**'
      - '.github/workflows/indexer-ci.yml'
  pull_request:
    branches: [main, develop]
    paths:
      - 'indexer/**'

jobs:
  test:
    name: Test Indexer
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
          cache-dependency-path: 'indexer/pnpm-lock.yaml'
      
      - name: Install dependencies
        working-directory: indexer
        run: pnpm install --frozen-lockfile
      
      - name: Type check
        working-directory: indexer
        run: pnpm exec tsc --noEmit
      
      - name: Build
        working-directory: indexer
        run: pnpm build
      
      - name: Run tests
        working-directory: indexer
        run: pnpm test

